import Link from "next/link";
import Image from "next/image";
import config from "@/config";
import { getSEOTags } from "@/libs/seo";
import { getPageFaqs } from "@/libs/pageFaqs";
import Faq from "@/components/brand/Faq";
import { FaqSchema } from "@/components/brand/Schema";
import { ProjectCards, ProjectCTA } from "@/components/brand/ServicePage";
import { getPortfolioProjects } from "@/libs/portfolio-projects";
export const metadata=getSEOTags({title:"Our Workmanship Guarantee | Better Homes",description:"Better Homes workmanship cover: ten years for extensions and lofts, two for kitchens and bathrooms, one for decorating. Clear handover and aftercare.",canonicalUrlRelative:"/our-guarantee"});
const faqs=[{question:"What does the workmanship guarantee cover?",answer:"The guarantee relates to our workmanship within the agreed scope. Extensions and loft conversions carry ten years, kitchen and bathroom work two years, and painting and decorating one year. The written terms explain coverage, conditions and how to raise an issue."},{question:"Are product warranties the same as workmanship cover?",answer:"No. Manufacturer warranties apply to products such as appliances, glazing or fittings. They are separate from our workmanship guarantee and from the business insurance cover."},{question:"How do I report a problem after handover?",answer:"Contact your project aftercare lead or raise a support request through your client portal. Describe the issue, where it is and when you noticed it, and add photographs where useful."},{question:"What will my project cost?",answer:"Full bathroom redesigns typically start around £12,000 and kitchen redesigns around £20,000. Substantial whole-home projects are typically £80,000 to £250,000+. Your quotation confirms the precise scope, VAT, allowances and payment stages."},{question:"How are payment stages agreed?",answer:"Your written quotation and contract set out payment stages. The existing initial deposit range is £300 to £1,000, depending on the project. Check the amount and subsequent stages in your own agreed documents."}];
export default function Page(){return <main><section className="bh-wrap bh-section"><p className="bh-eyebrow">Aftercare</p><h1 className="bh-title">Confidence that continues after handover.</h1><p className="bh-lead">We complete a snagging review and provide the relevant handover documents and workmanship terms. You have a clear point of contact if something needs attention afterwards.</p><dl className="bh-facts" style={{marginTop:48}}><div><dt>Extensions and loft conversions</dt><dd>10 years</dd></div><div><dt>Kitchen and bathroom work</dt><dd>2 years</dd></div><div><dt>Painting and decorating</dt><dd>1 year</dd></div></dl><p className="bh-small" style={{marginTop:24}}>Workmanship terms depend on the scope delivered. Product warranties and £10M insurance cover are separate from the workmanship guarantee.</p><div className="bh-actions"><Link href="/dashboard/tickets" className="bh-button">Request aftercare support</Link><Link href="/contact" className="bh-text-link">Contact the team</Link></div></section><Faq items={faqs}/><FaqSchema items={faqs} path="/our-guarantee"/></main>;}